### ISSUE TITLE
False positive for plugin invocation

### ISSUE THREAD

**Issue by cidrblock** [ansible-community/pytest-ansible#130]
If a fixture or param like `ansible_result` is used, it is assumed to be a fixture from this plugin.

We should be checking a real list of fixture names from the plugin and note in the README that they are reserved names in use by the plugin.

https://github.com/ansible-community/pytest-ansible/blob/150dfe781adfd0de5f9e0f450892c8ebe674f2d9/src/pytest_ansible/plugin.py#L235

Found with the AWS collection: https://github.com/ansible-collections/amazon.aws/blob/b53f7d727509cc36de45d98ad0dd403a001d7a73/tests/unit/plugins/modules/test_lambda_layer.py#L124

**Comment by Ruchip16** [comment]
i guess this should be fixed in the #152
