### ISSUE TITLE
How to access host variables?

### ISSUE THREAD

**Issue by jrjsmrtn** [ansible-community/pytest-ansible#33]
Is there an easy way to access the host variables of hosts returned by `ansible_adhoc`? 

Some custom variables are defined in our inventories and I need those to perform my tests. Those hosts are not Linux machines so I cannot use `ansible_adhoc.setup()` or `ansible_facts`.

I see that `ansible_adhoc()[inventory_hostname].options` has `inventory_manager` and `variable_manager` items, but I don't see how to get a specific host's variables.

Any idea?

**Comment by jrjsmrtn** [comment]
OK, I found this:

```python
@pytest.mark.parametrize(
    "inventory_hostname",
    ["host1", "host2", "host3"]
)
def test_something(ansible_adhoc, inventory_hostname):
    hosts = ansible_adhoc()

    host = hosts[inventory_hostname]
    host_vars = hosts.options["inventory_manager"].get_host(inventory_hostname).vars
    ...
```

Is this the way to go? Or is there another (simpler) method?

**Comment by kdelee** [comment]
Nope that is about it AFAIK

I think there is also a `get_vars` method that is probably safer than accessing `.vars` in case there are no vars.

A method you might try (this is pseudocode)
```
@pytest.fixture
def hostvars_for_host(ansible_adhoc):
    manager = ansible_adhoc.options()['inventory_manager']
    def get_hostvars(host_name):
        host = manager.get_host(host_name)
        return host.get_vars()
return get_hostvars

@pytest.mark.parametrize(
    "inventory_hostname",
    ["host1", "host2", "host3"]
)
def test_something(ansible_adhoc, hostvars_for_host, inventory_hostname):
    host_vars = hostvars_for_host(inventory_hostname)
```

That way you can re-use the logic in lots of places

**Comment by Zokormazo** [comment]
It happens the above solution only checks for vars defined in the host itself and does not inherit the ones coming from groups:

```
@pytest.fixture
def hostvars_for_host(ansible_adhoc):
    manager = ansible_adhoc.options()['inventory_manager']
    variable_manager = ansible_adhoc.options()['variable_manager']
    def get_hostvars(host_name):
        host = manager.get_host(host_name)
        return variable_manager.get_vars(host=host)
return get_hostvars

@pytest.mark.parametrize(
    "inventory_hostname",
    ["host1", "host2", "host3"]
)
def test_something(ansible_adhoc, hostvars_for_host, inventory_hostname):
    host_vars = hostvars_for_host(inventory_hostname)
```

Using `variable_manager` you'll get the ones defined via groups too
