### ISSUE TITLE
When installing with ansible 2.10 or higher installed, it uninstalls ansible and reinstalls 2.9

### ISSUE THREAD

**Issue by joej164** [ansible-community/pytest-ansible#54]
Thinking it needs updating to support newer versions of ansible.

**Comment by kdelee** [comment]
Yes! PRs welcome

**Comment by nordicmachine** [comment]
Definitely needs updating to specifically handle the versions of Ansible community > 3.0.0 (see https://www.ansible.com/blog/ansible-3.0.0-qa).

**Comment by CFSNM** [comment]
This issue should be fixed by https://github.com/ansible-community/pytest-ansible/pull/67

**Comment by Ruchip16** [comment]
closing the issue as #67 has been merged
