### ISSUE TITLE
check mode supported?

### ISSUE THREAD

**Issue by dbarrosop** [ansible-community/pytest-ansible#9]
Hello,
running a module in check mode doesn't seem to be supported, is that right?

Thanks!
David

**Comment by jlaska** [comment]
@dbarrosop oops, that's correct.  More omission than intent.  I'll include this in the next release.

**Comment by dbarrosop** [comment]
Hi! @jlaska, do you have an ETA on when you might release 2.0.0? : )

**Comment by jlaska** [comment]
@dbarrosop "real soon now" :).  Seriously though, there's a branch available if you'd like to help flush out remaining hiccups.  The planned remaining work on my end involves bug fixes and updates to `README.md`.  

https://github.com/jlaska/pytest-ansible/tree/host_manager

I'm slowly deprecating the old `ansible_module` fixture in favor of `ansible_adhoc` and `localhost`.  They should continue to work in the meantime.  Please let me know if you have any issues.  Feel free to raise as new issues.  Thanks!
